### PR TITLE
Do not assume FormData is JSON. Allow it to be passed in directly to XHR...

### LINKED ISSUE #13: POST with FormData data turns it into JSON
Trying to POST with a `FormData` instance gives the request a header of `application/json`. It should not add a header, and allow XHR to serialize FormData and add a `multipart/form-data` header.

Also, really nice lib :)

### PR DESCRIPTION
**Pull request by rgalanakis**
... so it can be serialized properly.

Fixes #13

### CODE REVIEW

**Comment by gre** [comment]
Make sense. Unfortunately it will break the node.js support because FormData is not defined in Node. Also I think this will also break on old IE version (Qajax supports IE6+).


I'm wondering what is the best way to fix that. 

I suggest to pass in `(window.FormData || function(){})` from https://github.com/gre/qajax/blob/master/src/browser.js. The https://github.com/gre/qajax/blob/master/src/node.js version would just pass a `function(){}`.

(this empty function ensure that FormData is not undefined: `foo instanceof (function(){})` will always be false)

**Comment by gre** [comment]
this should be fixed in 1.3.0

**Comment by gre** [comment]
keep your PR open because I'll likely take your cool test :) (I quickly fixed it recently because I also needed the feature)

**Comment by rgalanakis** [comment]
I've updated the PR so it's rebased from HEAD and contains just the specs. Should be good to merge.

**Comment by gre** [comment]
cool thanks

**Pull request merged**
